// src/app/layout.js
import { Inter } from 'next/font/google';
import UserLayout from '../components/layouts/UserLayout';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'CSC PNJ',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserLayout>{children}</UserLayout>
      </body>
    </html>
  );
}
